### ISSUE TITLE
Can I skip Downloads from monitored directories?

### ISSUE THREAD

**Issue by zpdcodes** [AppImage/appimaged#103]
I don't really want to register every AppImage downloaded. Is there any option to skip `$HOME/Downloads` folder?

**Comment by probonopd** [comment]
No, this is not possible with `appimaged`, it scans this directory by default so that every AppImage you download becomes automatically integrated. If you want finer control, then maybe you will like [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) by @TheAssassin instead of `appimaged` better.

**Comment by zpdcodes** [comment]
@probonopd Thanks for reply. I ended up on creating desktop file manually yet.

**Comment by TheAssassin** [comment]
You're recommended to use some sort of integration system, though. Please consider installing AppImageLauncher, even if just the Lite version. Desktop integration consists of much more than desktop files.
