### ISSUE TITLE
filename + version....

### ISSUE THREAD

**Issue by opqriu** [AppImage/appimaged#112]
I don't want the version number to appear in the file name.
Is there a way to do this?

**Comment by probonopd** [comment]
Hello @opqriu, no. There is always the application and the version shown. This is because you can have multiple versions of the same app at the same time.

Without this it would be very confusing:

![](https://user-images.githubusercontent.com/2480569/82724599-be657800-9cc6-11ea-8558-2a5b01a289a4.png)
