### ISSUE TITLE
Unable to build due to change in libappimage

### ISSUE THREAD

**Issue by genderquery** [AppImage/appimaged#72]
Build fails with the following error message:
```make[2]: *** No rule to make target 'lib/libappimage/XdgUtils-EXTERNAL-prefix/src/XdgUtils-EXTERNAL-build/src/DesktopEntry/libDesktopEntry.a', needed by 'src/appimaged'.  Stop.```

The name of `libDesktopEntry.a` has changed to `libXdgUtilsDesktopEntry.a` as of https://github.com/AppImage/libappimage/commit/a324a27e7c15cb4b9eb4598d7224158625959fc6

The solution is to simple update the libappimage submodule.

**Comment by probonopd** [comment]
Can you confirm @azubieta?

(Point in case for a [monorepo](https://github.com/AppImage/AppImageKit/issues/931): If everything was in one place, chnaging the name to libXdgUtilsDesktopEntry would immediately have shown up as a broken build unless it would have been fixed in all places at the same time.)

**Comment by azubieta** [comment]
In this case, the blame is on me. I broke it by changing the xdg-utils-cx binary names. Also if we use the cmake config script instead of a cmake external target this issue will not have happened.

**Comment by probonopd** [comment]
Thanks @genderquery and @azubieta
